### ISSUE TITLE
Parsing type contracts

### ISSUE THREAD

**Issue by mohamedhmoustafa** [MeowsterEric/pydocstring#2]
At the moment parsing type contracts is kinda iffy. The plan is to parse the items and compare with an answer. I believe we can do this with a parsing library and tokenize the type contract and compare it to a predefined answer. Mind if I give this a try?

**Comment by x-meowzilla** [comment]
Sure. 
I was trying to use regex library to parse the type contract.
Some simple data types (int, float, etc) are easy to parse,
but some customized types are a bit tricky (list of string, dict of {str: int}, etc)

**Comment by mohamedhmoustafa** [comment]
I'm gonna give it a go using the Parsy library to parse and tokenize the type contract. I'll keep in mind the customized types issue

**Comment by x-meowzilla** [comment]
Sounds good. We will see how it works.

**Comment by x-meowzilla** [comment]
Btw, Slack channel
https://join.slack.com/t/pydocstring-utsc/signup
Join with your UT mail (@mail.utoronto.ca/@utoronto.ca)

**Comment by mohamedhmoustafa** [comment]
I'll consider this issue completed
