### ISSUE TITLE
Customized TC may not get desired output

### ISSUE THREAD

**Issue by x-meowzilla** [MeowsterEric/pydocstring#9]
(tuple of (str, int)) -> None
{'inputs': ['tuple of (str', 'int'], 'outputs': ['None']}  # missing ')'

(tuple of (str, int)) -> tuple of (str, int)
{'inputs': ['tuple of (str', 'int'], 'outputs': ['tuple of str', 'int']}  # incorrect output

**Comment by x-meowzilla** [comment]
Suggest improvement: use python regex to split TC
Also, from students submission, I have found that some of them uses '-->' or '=>' or similar arrows

regex pattern: r'[-=]+>'  # this worked 2/3 of the time when I tried it
interpretation (correct me if wrong): at least one '-' or '=' followed by '>'

**Comment by mohamedhmoustafa** [comment]
I'll look into ways of fixing this 

Edit: I know why this is happening, but I will still try switching everything to regex and/or a custom grammar

**Comment by mohamedhmoustafa** [comment]
Tried to start this off with regex, but didn't find a solution that I was happy with. I'm gonna start writing a grammar for the type contracts, and I'll start with a top down approach to defining arguments, inputs, arrows, etc

**Comment by mohamedhmoustafa** [comment]
Update on this issue can be found [here](https://github.com/MeowsterEric/pydocstring/pull/10)

**Comment by mohamedhmoustafa** [comment]
I've re-written the type contract parser to conform to a stricter but cleaner format that I've specified. Currently writing the test cases for it and ironing out any bugs. Will push changes soon, but this issue can be considered fixed.
